apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring

# Diğer kaynaklar için gerekli YAML konfigürasyonlarını buraya ekleyin
